#!/usr/bin/env python3
"""Coordinator-driven multi-agent development flow for snake demo."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from datetime import UTC, datetime
import json
from pathlib import Path
import subprocess
import sys
from typing import Any


@dataclass(frozen=True)
class DevTask:
    task_id: str
    owner: str
    description: str
    boundary: tuple[str, ...]
    kind: str


def _iso_now() -> str:
    return datetime.now(tz=UTC).isoformat()


def _default_coordinator_script() -> Path:
    # .../.agents/skills/custom/coordinator/examples/snake/snake_devflow.py
    # -> .../.agents/skills/custom/coordinator/scripts/coordinator.py
    return Path(__file__).resolve().parents[2] / "scripts" / "coordinator.py"


def _run(cmd: list[str], cwd: Path, check: bool = True) -> subprocess.CompletedProcess[str]:
    proc = subprocess.run(cmd, cwd=str(cwd), text=True, capture_output=True, check=False)
    if check and proc.returncode != 0:
        raise RuntimeError(
            f"command failed rc={proc.returncode}: {' '.join(cmd)}\nstdout={proc.stdout}\nstderr={proc.stderr}"
        )
    return proc


def _run_json(cmd: list[str], cwd: Path, check: bool = True) -> dict[str, Any]:
    proc = _run(cmd, cwd=cwd, check=check)
    text = proc.stdout.strip()
    if not text:
        raise RuntimeError(f"empty stdout: {' '.join(cmd)}")
    return json.loads(text)


def _git(repo: Path, *args: str, check: bool = True) -> subprocess.CompletedProcess[str]:
    return _run(["git", *args], cwd=repo, check=check)


def _git_json(repo: Path, *args: str) -> dict[str, Any]:
    proc = _git(repo, *args)
    return json.loads(proc.stdout.strip())


def _git_stdout(repo: Path, *args: str) -> str:
    return _git(repo, *args).stdout.strip()


def _has_staged_changes(repo: Path) -> bool:
    return bool(_git_stdout(repo, "diff", "--cached", "--name-only"))


def _detect_repo_root(cwd: Path) -> Path:
    proc = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        cwd=str(cwd),
        text=True,
        capture_output=True,
        check=False,
    )
    if proc.returncode != 0:
        raise RuntimeError(
            "cannot detect git repo from current directory; "
            "run inside target repo or provide --repo-root explicitly"
        )
    return Path(proc.stdout.strip()).resolve()


def _ensure_clean_repo(repo: Path) -> None:
    inside = _git_stdout(repo, "rev-parse", "--is-inside-work-tree")
    if inside != "true":
        raise RuntimeError(f"not a git repo: {repo}")
    dirty = _git_stdout(repo, "status", "--porcelain")
    if dirty:
        raise RuntimeError("repo has uncommitted changes; aborting devflow")


def _read_template(name: str) -> str:
    return (Path(__file__).resolve().parent / name).read_text(encoding="utf-8")


def _write_text(repo: Path, relpath: str, text: str) -> None:
    path = repo / relpath
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _build_tasks() -> list[DevTask]:
    return [
        DevTask(
            task_id="T1-core",
            owner="agent-core",
            description="build snake engine core",
            boundary=("snake_demo/snake_core.py",),
            kind="core",
        ),
        DevTask(
            task_id="T2-policy",
            owner="agent-policy",
            description="build multi-agent policy",
            boundary=("snake_demo/snake_agents.py",),
            kind="policy",
        ),
        DevTask(
            task_id="T3-runner",
            owner="agent-runner",
            description="build executable runner",
            boundary=("snake_demo/snake_runner.py",),
            kind="runner",
        ),
        DevTask(
            task_id="T4-integrate",
            owner="agent-integrator",
            description="add generated test and doc",
            boundary=("snake_demo/README.generated.md", "tests/test_snake_generated.py"),
            kind="integrator",
        ),
    ]


def _generated_readme() -> str:
    return """# Generated Snake Demo\n\nThis directory is generated by snake_devflow multi-agent pipeline.\n\nRun:\n\n```bash\npython3 snake_demo/snake_runner.py --steps 60 --tick-ms 0 --no-render\n```\n"""


def _generated_test() -> str:
    return """import json\nimport subprocess\nimport unittest\nfrom pathlib import Path\n\n\nRUNNER = Path(__file__).resolve().parents[1] / \"snake_demo\" / \"snake_runner.py\"\n\n\nclass GeneratedSnakeTests(unittest.TestCase):\n    def test_generated_runner_smoke(self) -> None:\n        proc = subprocess.run(\n            [\"python3\", str(RUNNER), \"--steps\", \"30\", \"--tick-ms\", \"0\", \"--no-render\"],\n            text=True,\n            capture_output=True,\n            check=False,\n        )\n        self.assertEqual(proc.returncode, 0, proc.stdout + proc.stderr)\n        payload = json.loads(proc.stdout.strip().splitlines()[-1])\n        self.assertEqual(payload[\"status\"], \"ok\")\n\n\nif __name__ == \"__main__\":\n    unittest.main()\n"""


class CoordinatorClient:
    def __init__(self, script_path: Path, state_root: Path) -> None:
        self.script_path = script_path
        self.state_root = state_root

    def _base(self) -> list[str]:
        return [sys.executable, str(self.script_path), "--state-root", str(self.state_root)]

    def run(self, *, topic: str, from_agent: str, to_agents: list[str]) -> dict[str, Any]:
        return _run_json(
            [
                *self._base(),
                "run",
                "--topic",
                topic,
                "--from-agent",
                from_agent,
                "--to-agents",
                ",".join(to_agents),
                "--hold-open",
                "--worker-mode",
                "none",
            ],
            cwd=Path.cwd(),
        )

    def stat(self, job_id: str) -> dict[str, Any]:
        return _run_json([*self._base(), "stat", job_id], cwd=Path.cwd())

    def relay(self, *, job_id: str, trace_id: str, from_agent: str, to_agent: str, intent: str, payload_text: str) -> None:
        _run_json(
            [
                *self._base(),
                "relay-send",
                job_id,
                "--from-agent",
                from_agent,
                "--to-agent",
                to_agent,
                "--intent",
                intent,
                "--payload-text",
                payload_text,
                "--trace-id",
                trace_id,
            ],
            cwd=Path.cwd(),
        )

    def stop(self, job_id: str) -> None:
        _run_json([*self._base(), "stop", job_id], cwd=Path.cwd(), check=False)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Master/worker multi-agent development pipeline for snake demo.")
    parser.add_argument(
        "--repo-root",
        default="",
        help=(
            "Target git repo where branches and integration happen. "
            "Default: auto-detect from current working directory."
        ),
    )
    parser.add_argument("--state-root", default=str(Path.home() / ".agents" / "state" / "coordinator"))
    parser.add_argument("--topic", default="snake-devflow")
    parser.add_argument("--from-agent", default="master-agent")
    parser.add_argument("--base-branch", default="")
    parser.add_argument("--smoke-steps", type=int, default=40)
    parser.add_argument("--summary-out", default="")
    parser.add_argument("--coordinator-script", default=str(_default_coordinator_script()))
    return parser.parse_args()


def _task_outputs(repo: Path, task: DevTask) -> list[str]:
    if task.kind == "core":
        _write_text(repo, "snake_demo/snake_core.py", _read_template("snake_core.py"))
        return ["snake_demo/snake_core.py"]
    if task.kind == "policy":
        _write_text(repo, "snake_demo/snake_agents.py", _read_template("snake_agents.py"))
        return ["snake_demo/snake_agents.py"]
    if task.kind == "runner":
        _write_text(repo, "snake_demo/snake_runner.py", _read_template("snake_runner.py"))
        return ["snake_demo/snake_runner.py"]
    _write_text(repo, "snake_demo/README.generated.md", _generated_readme())
    _write_text(repo, "tests/test_snake_generated.py", _generated_test())
    return ["snake_demo/README.generated.md", "tests/test_snake_generated.py"]


def main() -> int:
    args = _parse_args()
    repo = Path(args.repo_root).expanduser().resolve() if args.repo_root.strip() else _detect_repo_root(Path.cwd())
    state_root = Path(args.state_root).expanduser().resolve()

    _ensure_clean_repo(repo)
    base_branch = args.base_branch.strip() or _git_stdout(repo, "rev-parse", "--abbrev-ref", "HEAD")
    tasks = _build_tasks()
    to_agents = sorted({task.owner for task in tasks})

    client = CoordinatorClient(
        script_path=Path(args.coordinator_script).expanduser().resolve(),
        state_root=state_root,
    )

    run_payload = client.run(topic=args.topic, from_agent=args.from_agent, to_agents=to_agents)
    job_id = str(run_payload["job_id"])
    trace_id = str(run_payload["trace_id"])
    stat_payload = client.stat(job_id)
    branches = dict(stat_payload["job"].get("branches", {}))

    # Master planning todo and boundary assignment.
    todo_rows = []
    for task in tasks:
        todo_rows.append(
            {
                "task_id": task.task_id,
                "owner": task.owner,
                "description": task.description,
                "boundary": list(task.boundary),
                "branch": branches.get(task.owner, f"agent/{task.owner}/{args.topic}"),
            }
        )

    todo_payload = {
        "generated_at": _iso_now(),
        "topic": args.topic,
        "from_agent": args.from_agent,
        "base_branch": base_branch,
        "job_id": job_id,
        "trace_id": trace_id,
        "tasks": todo_rows,
    }
    _write_text(repo, "snake_demo/TODO.multiagent.json", json.dumps(todo_payload, ensure_ascii=False, indent=2) + "\n")
    _git(repo, "add", "snake_demo/TODO.multiagent.json")
    _git(repo, "commit", "-m", "chore(snake): master plan and task boundaries")

    for row in todo_rows:
        client.relay(
            job_id=job_id,
            trace_id=trace_id,
            from_agent=args.from_agent,
            to_agent=row["owner"],
            intent="propose",
            payload_text=(
                f"assign {row['task_id']} branch={row['branch']} boundary={','.join(row['boundary'])}"
            ),
        )

    task_results: list[dict[str, Any]] = []
    merged_branches: list[str] = []

    try:
        for task in tasks:
            branch = branches.get(task.owner, f"agent/{task.owner}/{args.topic}")

            # Agent boundary handshake.
            for peer in to_agents:
                if peer == task.owner:
                    continue
                client.relay(
                    job_id=job_id,
                    trace_id=trace_id,
                    from_agent=task.owner,
                    to_agent=peer,
                    intent="propose",
                    payload_text=f"boundary handshake {task.task_id}: {','.join(task.boundary)}",
                )
                client.relay(
                    job_id=job_id,
                    trace_id=trace_id,
                    from_agent=peer,
                    to_agent=task.owner,
                    intent="answer",
                    payload_text=f"ack {task.task_id}",
                )

            _git(repo, "checkout", "-B", branch, base_branch)
            outputs = _task_outputs(repo, task)
            _git(repo, "add", *outputs)
            if _has_staged_changes(repo):
                _git(repo, "commit", "-m", f"feat(snake): {task.task_id} {task.description}")
                commit_mode = "commit"
            else:
                commit_mode = "noop"
            commit_sha = _git_stdout(repo, "rev-parse", "HEAD")

            client.relay(
                job_id=job_id,
                trace_id=trace_id,
                from_agent=task.owner,
                to_agent=args.from_agent,
                intent="answer",
                payload_text=f"done {task.task_id} mode={commit_mode} commit={commit_sha[:12]}",
            )

            task_results.append(
                {
                    "task_id": task.task_id,
                    "owner": task.owner,
                    "branch": branch,
                    "outputs": outputs,
                    "commit_mode": commit_mode,
                    "commit": commit_sha,
                }
            )

        _git(repo, "checkout", base_branch)
        for row in task_results:
            _git(repo, "merge", "--no-ff", "-m", f"merge({row['owner']}): {row['task_id']}", row["branch"])
            merged_branches.append(row["branch"])

        smoke_proc = _run(
            [
                sys.executable,
                "snake_demo/snake_runner.py",
                "--steps",
                str(max(5, args.smoke_steps)),
                "--tick-ms",
                "0",
                "--no-render",
            ],
            cwd=repo,
        )
        smoke_payload = json.loads(smoke_proc.stdout.strip().splitlines()[-1])

        _run([sys.executable, "-m", "unittest", "-v", "tests/test_snake_generated.py"], cwd=repo)

        client.relay(
            job_id=job_id,
            trace_id=trace_id,
            from_agent="agent-integrator",
            to_agent=args.from_agent,
            intent="answer",
            payload_text=f"integration done smoke={smoke_payload['result']} score={smoke_payload['score']}",
        )

        summary = {
            "status": "ok",
            "repo_root": str(repo),
            "base_branch": base_branch,
            "job_id": job_id,
            "trace_id": trace_id,
            "todo_file": str(repo / "snake_demo" / "TODO.multiagent.json"),
            "tasks": task_results,
            "merged_branches": merged_branches,
            "smoke": smoke_payload,
            "state_root": str(state_root),
        }
    finally:
        client.stop(job_id)

    if args.summary_out:
        out = Path(args.summary_out).expanduser().resolve()
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(summary, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    print(json.dumps(summary, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
